# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: utf-8


spring:
  # 配置数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost/codeplayer-blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  # 配置RabbitMq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  # 禁用ThymeLeaf缓存
  thymeleaf:
    cache: false

# 配置保存日志相关
logging:
  level:
    root: info
    com:
      codepalyer:
        mapper: debug
  file:
    name: logs/codeplayer-blog.log
  logback:
    rollingpolicy:
      total-size-cap: 10MB
      max-history: 3

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 修改成自己的
github:
  client:
    id: xxx
    secret: xxx
  redirect:
    url: http://localhost:80/callback


